# Generated by Django 5.0.2 on 2024-03-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='licence_number',
            new_name='document_number',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='address_verification',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='business_image',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='business_registration_date',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='passport_expiry_date',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='passport_image',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='passport_issued_country',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='photo_image',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='photo_issue_date',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='photo_number',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='registraion_number',
        ),
    ]
