# Generated by Django 5.0.2 on 2024-03-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_licence_number_kyc_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
