# Generated by Django 5.0.2 on 2024-03-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_scholorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholorship',
            name='remarks',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
